force-app/main/default/objects/IMDB_Movie__c/IMDB_Movie__c.object-meta.xml
<CustomObject>
    <label>IMDB Movie</label>
    <nameField>
        <displayFormat>M-{0}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Id__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Id__c</fullName>
    <externalId>true</externalId>
    <label>IMDB Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IMDB_MovieTriggerHandler.cls
public with sharing class IMDB_MovieTriggerHandler {
    public static void onBeforeInsert(List<IMDB_Movie__c> listOfNewMovies) {
        for (IMDB_Movie__c newMovie : listOfNewMovies) {
            newMovie.IMDB_Unique_Id__c = newMovie.IMDB_Id__c + '-' + newMovie.OwnerId;
        }
    }

    public static void onBeforeUpdate(List<IMDB_Movie__c> listOfNewMovies, Map<Id,IMDB_Movie__c> mapOfOldMoviesById) {
        for (IMDB_Movie__c newMovie : listOfNewMovies) {
            if (newMovie.IMDB_Id__c != mapOfOldMoviesById.get(newMovie.Id).IMDB_Id__c)
            newMovie.IMDB_Unique_Id__c = newMovie.IMDB_Id__c + '-' + newMovie.createdById;
        }
    }
}