force-app/main/default/objects/IMDB_Movie__c/IMDB_Movie__c.object-meta.xml
<CustomObject>
    <label>IMDB Movie</label>
    <nameField>
        <displayFormat>M-{0}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Content_Rating__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Content_Rating__c</fullName>
    <label>Content Rating</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Description__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Genres__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Genres__c</fullName>
    <label>Genres</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Id__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Id__c</fullName>
    <externalId>true</externalId>
    <label>IMDB Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Image_URL__c</fullName>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Metacritic_Rating__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Metacritic_Rating__c</fullName>
    <label>Metacritic Rating</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Plot__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Plot__c</fullName>
    <label>Plot</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Rating__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Rating__c</fullName>
    <label>IMDB Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Rating_Votes__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Rating_Votes__c</fullName>
    <label>IMDB Rating Votes</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Runtime__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Runtime__c</fullName>
    <label>Runtime</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Stars__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Stars__c</fullName>
    <label>Stars</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Title__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IMDB_FavoritesCtrl.cls
public with sharing class IMDB_FavoritesCtrl {
    @AuraEnabled
    public static String queryAddedMovies() {
        List<IMDB_MovieItemCtrl.MovieWrapper> listOfMovieWrappers = new List<IMDB_MovieItemCtrl.MovieWrapper>();
        try {
            List<IMDB_Movie__c> listOfMovies = [
                SELECT
                    IMDB_Content_Rating__c,
                    IMDB_Description__c,
                    IMDB_Genres__c,
                    IMDB_Image_URL__c,
                    IMDB_Id__c,
                    IMDB_Rating__c,
                    IMDB_Rating_Votes__c,
                    IMDB_Metacritic_Rating__c,
                    IMDB_Plot__c,
                    IMDB_Runtime__c,
                    IMDB_Stars__c,
                    IMDB_Title__c
                FROM IMDB_Movie__c
                WHERE OwnerId = :UserInfo.getUserId()
            ];
            for (IMDB_Movie__c movie : listOfMovies) {
                IMDB_MovieItemCtrl.MovieWrapper wrapper = new IMDB_MovieItemCtrl.MovieWrapper();
                wrapper.id = movie.IMDB_Id__c;
                wrapper.title = movie.IMDB_Title__c;
                wrapper.description = movie.IMDB_Description__c;
                wrapper.image = movie.IMDB_Image_URL__c;
                wrapper.runtimeStr = movie.IMDB_Runtime__c;
                wrapper.genres = movie.IMDB_Genres__c;
                wrapper.contentRating = movie.IMDB_Content_Rating__c;
                wrapper.imDbRating = movie.IMDB_Rating__c;
                wrapper.imDbRatingVotes = movie.IMDB_Rating_Votes__c;
                wrapper.metacriticRating = movie.IMDB_Metacritic_Rating__c;
                wrapper.plot = movie.IMDB_Plot__c;
                wrapper.stars = movie.IMDB_Stars__c;
                wrapper.isAdded = true;
                listOfMovieWrappers.add(wrapper);
            }
        } catch (Exception catchedException) {
            AuraHandledException error = new AuraHandledException(
                System.Label.Records_updated_error
            );
            error.setMessage(System.Label.Records_updated_error);
            System.debug(catchedException.getMessage());
            throw error;
        }
        return JSON.serialize(listOfMovieWrappers);
    }
}