force-app/main/default/objects/IMDB_Movie__c/IMDB_Movie__c.object-meta.xml
<CustomObject>
    <label>IMDB Movie</label>
    <nameField>
        <displayFormat>M-{0}</displayFormat>
        <label>Movie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Content_Rating__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Content_Rating__c</fullName>
    <label>Content Rating</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Description__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Genres__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Genres__c</fullName>
    <label>Genres</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Id__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Id__c</fullName>
    <externalId>true</externalId>
    <label>IMDB Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Image_URL__c</fullName>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Metacritic_Rating__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Metacritic_Rating__c</fullName>
    <label>Metacritic Rating</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Plot__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Plot__c</fullName>
    <label>Plot</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Rating__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Rating__c</fullName>
    <label>IMDB Rating</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Rating_Votes__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Rating_Votes__c</fullName>
    <label>IMDB Rating Votes</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Runtime__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Runtime__c</fullName>
    <label>Runtime</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Stars__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Stars__c</fullName>
    <label>Stars</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IMDB_Movie__c/fields/IMDB_Title__c.field-meta.xml
<CustomField>
    <fullName>IMDB_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IMDB_MovieItemCtrl.cls
public with sharing class IMDB_MovieItemCtrl {
    @AuraEnabled
    public static void addMovieToFavorites(String jsonMovie) {
        try {
            MovieWrapper movie = (MovieWrapper) JSON.deserialize(
                jsonMovie,
                MovieWrapper.class
            );
            insertMovieFromWrapper(movie);
        } catch (Exception catchedException) {
            AuraHandledException error = new AuraHandledException(
                System.Label.Records_updated_error
            );
            error.setMessage(System.Label.Records_updated_error);
            System.debug(catchedException.getMessage());
            throw error;
        }
    }

    @AuraEnabled
    public static void removeMovieFromFavorites(String externalId) {
        try {
            delete [
                SELECT Id
                FROM IMDB_Movie__c
                WHERE IMDB_Id__c = :externalId
            ];
        } catch (Exception catchedException) {
            AuraHandledException error = new AuraHandledException(
                System.Label.Records_updated_error
            );
            error.setMessage(System.Label.Records_updated_error);
            System.debug(catchedException.getMessage());
            throw error;
        }
    }

    public static void insertMovieFromWrapper(MovieWrapper movieWrapper) {
        // Decimal runtimeDecimal;
        // if (movieWrapper.runtimeStr != null) {
        //     runtimeDecimal = Decimal.valueOf(movieWrapper.runtimeStr.replaceAll('min', '').trim());
        //     System.debug(runtimeDecimal);
        // }
        IMDB_Movie__c movie = new IMDB_Movie__c(
            IMDB_Id__c = movieWrapper.id,
            IMDB_Title__c = movieWrapper.title,
            IMDB_Description__c = movieWrapper.description,
            IMDB_Image_URL__c = movieWrapper.image,
            IMDB_Runtime__c = movieWrapper.runtimeStr,
            IMDB_Genres__c = movieWrapper.genres,
            IMDB_Content_Rating__c = movieWrapper.contentRating,
            IMDB_Rating__c = movieWrapper.imDbRating,
            IMDB_Rating_Votes__c = movieWrapper.imDbRatingVotes,
            IMDB_Metacritic_Rating__c = movieWrapper.metacriticRating,
            IMDB_Plot__c = movieWrapper.plot,
            IMDB_Stars__c = movieWrapper.stars
        );
        insert movie;
    }

    public class MovieWrapper {
        public String id { get; set; }
        public String image { get; set; }
        public String title { get; set; }
        public String description { get; set; }
        public String runtimeStr { get; set; }
        public String genres { get; set; }
        public String contentRating { get; set; }
        public Decimal imDbRating { get; set; }
        public Decimal imDbRatingVotes { get; set; }
        public Decimal metacriticRating { get; set; }
        public String plot { get; set; }
        public String stars { get; set; }
        public Boolean isAdded { get; set; }
    }
}